refactor: update readme + add prod env

diff --git a/start-k8s b/start-k8s
--- a/start-k8s
+++ b/start-k8s
@@ -2,11 +2,14 @@
 set -eu
 # example use case: ./start-k8s-shiny production
 # Set the environment variable to the first command-line argument or default to 'testing'
-ENV=${1:-dev}
-if [[ "$ENV" != "dev" && "$ENV" != "production" ]]; then
-    echo "Error: env must be either 'dev' or 'production'"
+ENV=${1:-staging}
+if [[ "$ENV" != "staging" && "$ENV" != "production" ]]; then
+    echo "Error: env must be either 'staging' or 'production'"
     exit 1
 fi
+export VAULT_ADDR=https://vault.dide.ic.ac.uk:8200
+export VAULT_TOKEN=$(vault login -method=github -token-only)
+
 # Make the script itself executable
 chmod +x "$0"
 
@@ -17,10 +20,10 @@ chmod +x k8s/
 kubectl create namespace beebop --dry-run=client -o yaml | kubectl apply -f -
 
 # Run the script to configure SSL (assuming it's in the k8s directory)
-k8s/configure_ssl ||  { echo "Error: Failed to configure SSL"; exit 1; }
+k8s/configure_ssl  ||  { echo "Error: Failed to configure SSL"; exit 1; }
 
 # Run the script to configure secrets (assuming it's in the k8s directory)
-k8s/configure_secrets ||  { echo "Error: Failed to configure secrets"; exit 1; }
+k8s/configure_secrets  ||  { echo "Error: Failed to configure secrets"; exit 1; }
 
 # Apply Kubernetes manifests from overlays based on the specified or default environment
 kubectl apply -k "k8s/overlays/$ENV"
