feat: env to ssl + secrets

diff --git a/k8s/configure_secrets b/k8s/configure_secrets
--- a/k8s/configure_secrets
+++ b/k8s/configure_secrets
@@ -1,11 +1,17 @@
 #!/usr/bin/env bash
 set -eu
+
+ENV=${1:-staging}
+if [[ "$ENV" != "staging" && "$ENV" != "production" ]]; then
+    echo "Error: env must be either 'staging' or 'production'"
+    exit 1
+fi
 # assume already athenticated to vault
-# TODO: change for diffrenet enviroments (prod / staging)
-GOOGLE_CLIENT_ID=$(vault read -field=clientid /secret/beebop/auth/staging/google)
-GOOGLE_CLIENT_SECRET=$(vault read -field=secret /secret/beebop/auth/staging/google)
-GITHUB_CLIENT_ID=$(vault read -field=clientid /secret/beebop/auth/staging/github)
-GITHUB_CLIENT_SECRET=$(vault read -field=secret /secret/beebop/auth/staging/github)
+
+GOOGLE_CLIENT_ID=$(vault read -field=clientid /secret/beebop/auth/$ENV/google)
+GOOGLE_CLIENT_SECRET=$(vault read -field=secret /secret/beebop/auth/$ENV/google)
+GITHUB_CLIENT_ID=$(vault read -field=clientid /secret/beebop/auth/$ENV/github)
+GITHUB_CLIENT_SECRET=$(vault read -field=secret /secret/beebop/auth/$ENV/github)
 SESSION_SECRET=$(vault read -field=secret /secret/beebop/express-session)
 
 kubectl -n beebop create secret generic auth-secrets \
diff --git a/k8s/configure_ssl b/k8s/configure_ssl
--- a/k8s/configure_ssl
+++ b/k8s/configure_ssl
@@ -1,14 +1,17 @@
 #!/usr/bin/env bash
-# TODO: update to use vault k8s auth
-
 set -eu
-
+# assume already athenticated to vault
+ENV=${1:-staging}
+if [[ "$ENV" != "staging" && "$ENV" != "production" ]]; then
+    echo "Error: env must be either 'staging' or 'production'"
+    exit 1
+fi
 DEST=${PWD}/k8s/ssl
 mkdir -p $DEST 
 
-vault read -field=cert /secret/beebop/ssl/staging > \
+vault read -field=cert /secret/beebop/ssl/$ENV > \
       ${DEST}/certificate.pem
-vault read -field=key /secret/beebop/ssl/staging > \
+vault read -field=key /secret/beebop/ssl/$ENV > \
       ${DEST}/key.pem
 
 kubectl -n beebop create secret tls tls-secret --cert  ${DEST}/certificate.pem --key ${DEST}/key.pem
